name: Build release binaries

on:
  push
  # release:
  #   types:
  #     - published

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Cross-compile binaries
    runs-on: ${{ matrix.target.os }}
    strategy:
      matrix:
        target:
          - name: macOS - aarch64
            os: macos-latest
            target: aarch64-apple-darwin
          - name: GNU/Linux - aarch64
            os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
          - name: macOS - x86
            os: macos-latest
            target: x86_64-apple-darwin
          - name: Windows - x86
            os: windows-latest
            target: x86_64-pc-windows-msvc
          - name: GNU/Linux - x86
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
    steps:
      - uses: actions/checkout@v3
      - name: Install libdbus
        if: matrix.target.os == 'ubuntu-latest'
        run: sudo apt install libdbus-1-dev
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target.target }}
          override: true
      - name: Compile for ${{ matrix.target.name }}
        uses: actions-rs/cargo@v1
        with:
          use-cross: false
          command: build
          args: --verbose --release --target=${{ matrix.target.target }}
      - name: Rename binary
        run: mv target/${{ matrix.target.target }}/release/ydnc-time ./ydnc-time-${{ matrix.target.target }}
      - name: Upload ${{ matrix.target.name }} binary to release
        uses: softprops/action-gh-release@v1
        with:
          files: ydnc-time-${{ matrix.target.target }}
          fail_on_unmatched_files: true
